version: "3.8"

services:
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      spring.config.name: application-dev
    depends_on:
      - mysql-db
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - back-end
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  mysql-db:
    image: mysql:8.0.33
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: forum_db
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd

volumes:
  dbdata:
