version: "3.8"

services:
  back-end:
    image: 009160074177.dkr.ecr.ap-southeast-2.amazonaws.com/hecker-ground/back-end:latest
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  front-end:
    image: 009160074177.dkr.ecr.ap-southeast-2.amazonaws.com/hecker-ground/front-end:latest
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - back-end
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
  certbot:
    image: certbot/certbot:v2.6.0
    depends_on:
      - front-end
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt
    command:
      - certonly
      - --webroot
      - -w
      - /var/www/certbot/
      - --email=heckerground@gmail.com
      - --agree-tos
      - --no-eff-email
      - -d
      - heckerground.com
