FROM node:18-alpine3.18 AS build

WORKDIR /app

# COPY [host machine] [dest] (relative to DockerFile, relative to dest root)
COPY package.json .

COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx-dev.conf /etc/nginx/conf.d

COPY --from=build /app/build /usr/share/nginx/html/

ENTRYPOINT ["nginx", "-g", "daemon off;"]
